# Generated by Django 2.2.12 on 2022-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Aplikācijas nosaukums')),
                ('description', models.TextField(verbose_name='Apraksts')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Datums')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Laiks')),
            ],
        ),
    ]
