# Generated by Django 2.2.12 on 2022-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0002_auto_20221118_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Send notifications'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
