# Generated by Django 4.1.4 on 2022-12-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0004_auto_20221118_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nosaukums')),
                ('description', models.TextField(verbose_name='Apraksts')),
                ('email', models.EmailField(max_length=254, verbose_name='E-pasts')),
            ],
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['name'], 'verbose_name': 'Kompanija', 'verbose_name_plural': 'Kompanijas'},
        ),
    ]
