# Generated by Django 4.1.4 on 2022-12-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0005_company_alter_incident_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incidentapp.component'),
            preserve_default=False,
        ),
    ]
