# Generated by Django 4.1.4 on 2022-12-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapp', '0006_company_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Kompanija', 'verbose_name_plural': 'Kompanijas'},
        ),
    ]
